# Generated by Django 3.2.9 on 2021-12-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_num_resp_confiables'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='aprobacion',
            field=models.IntegerField(null=True),
        ),
    ]
